version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "dayly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "dayly" 
